Description: >
  Pablo Albaladejo / Bastion AWS-IaC

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  BastionHostKeyPair:
    Description: A key pair to access to the bastion host
    Type: String
    
Resources:
  BastionHostSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH access via port 22"
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"

  BastionHostInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref BastionHostSecurityGroup
      KeyName: !Ref BastionHostKeyPair
      ImageId: ami-06d51e91cea0dac8d
      SubnetId:
        Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"

Outputs:
  BastionHostIP:
    Description: "Public IP address of the BastionHost instance"
    Value:
      "Fn::GetAtt":
        - BastionHostInstance
        - PublicIp